### ISSUE TITLE
Use github.com/stretchr/testify/mock for unit tests

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-msoffice#3]
The recommended best practice at Mattermost is to use `github.com/stretchr/testify/mock` to mock interfaces in unit tests. In other plugins, like Jira, we had been constrained by the flat plugin package layout, and the existing data structures made it difficult to break it into subpackages.

This plugin was set up to avoid these issues, and the functionality is more carefully packaged, so using `github.com/stretchr/testify/mock` should be easy(-er).

**Comment by cpurta** [comment]
@levb I am currently addressing this issue in #2
